person:
  name: 张三
  age: 18
  birth-day: 2010/10/10
  like: true
  child:
    name: 李四
    age: 18
    birth-day: 2010/6/6
#    text: ["abc","def"]
    text:
      - abc
      - def
  dogs: [{name: 小黑,age: 1},{name: 小黄笑哈哈,age: 1}]
#    - name: 小黑
#      age: 1
#    - name: 小黄
#      age: 1
  cats:
    c1:
      name: 小白
      age: 2
    c2: {name: 小灰,age: 2}
#      name: 小灰
#      age: 2



